Analise de projeto/BiotLab.mdj

adicionado packages(Boundary, Contol, entity, Persistence.)  no analisy model.

Acidionado packges

---

Codigo/BiotLabWeb/BiotLabWeb/Controllers/HaremController.cs
Codigo/BiotLabWeb/BiotLabWeb/Mapper/HaremProfile.cs
Codigo/BiotLabWeb/BiotLabWeb/Models/HaremViewModel.cs
Codigo/BiotLabWeb/BiotLabWeb/Program.cs
Codigo/BiotLabWeb/BiotLabWeb/Views/Harem/Create.cshtml
Codigo/BiotLabWeb/BiotLabWeb/Views/Harem/Delete.cshtml
Codigo/BiotLabWeb/BiotLabWeb/Views/Harem/Details.cshtml
Codigo/BiotLabWeb/BiotLabWeb/Views/Harem/Edit.cshtml
Codigo/BiotLabWeb/BiotLabWeb/Views/Harem/Index.cshtml
Codigo/BiotLabWeb/Service/HaremService.cs
Codigo/BiotLabWeb/core/BiotLabContext.cs
Codigo/BiotLabWeb/core/Gaiola.cs
Codigo/BiotLabWeb/core/Harem.cs
Codigo/BiotLabWeb/core/Povoargaiola.cs
Codigo/BiotLabWeb/core/Service/IHaremService.cs

Foi Adicionado O Caso De Uso Manter Harem. (Service,Controller, models)

Adicionado o caso de uso Manter Harem.

---

Codigo/BiotLab/core/DTO/InstituicaoDTO.cs

os arquivos InstituicaoService, IInstituicaoService e Program já foram adicionados anteriormente

Implementado o InstituicaoDTO do CSU Manter Instituicao

---

Codigo/BiotLab/BiotLabWeb/Models/InstituicaoViewModel.cs
Codigo/BiotLab/core/DTO/InstituicaoDTO.cs

InstituicaoController e InstituicaoProfile que pertence ao mapper já foram adicionados anteriormente

Adicionado a InstituicaoViewModel ao projeto

---

Codigo/BiotLab/BiotLabWeb/Views/Instituicao/Create.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Instituicao/Delete.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Instituicao/Details.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Instituicao/Edit.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Instituicao/Index.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Shared/_Layout.cshtml

Adicionado o Create, Delete, Details, Edit e Index

Implementado as Views do caso de uso Manter Instituicao

---

Codigo/BiotLab/BiotLabWeb/Models/EntradaanestesicoViewModel.cs

Faltou adicionar as Views( create, edit, delete, details, index)

adicionado o models #closed119

---

Codigo/BiotLab/BiotLabWeb/Mapper/EntradaanestesicoProfile.cs
Codigo/BiotLab/ServiceTests/EntradaanestesicoTests.cs

Foi Adicionado A Classe Service Teste De Entradaanestesico, Seguindo o Padrão Do Projeto

Adicionado a classe ServiceTests/EntradaanestesicoTests 

---

Codigo/BiotLab/BiotLabWeb/Controllers/FornecedorController.cs
Codigo/BiotLab/BiotLabWeb/Mapper/FornecedorProfile.cs
Codigo/BiotLab/BiotLabWeb/Models/FornecedorViewModel.cs

Foi adicionado ao CSU manter fornecedor, mas o DTO e o program serão adicionados nas proximas issues

Adicionado FornecedorController, FornecedorProfile e FornecedorViewModel

---

Codigo/BiotLab/BiotLabTests/Controllers/EntradaanestesicoControllerTests.cs

Não conseguir testar porque o teste dessa controller depende de IAnestesicoService e de IEntradumService, que  falta ser implementada ao projeto,

Adicionado Controllers/EntradaanestesicoControllerTests 

---

Codigo/BiotLab/Service/GaiolaharemService.cs
Codigo/BiotLab/core/Service/IGaiolaharemService.cs

Foram Adicionado As Classes IGaiolaharemService e a GaiolaharemService

Adicionado a classe GaiolaharemService e a IGaiolaharemService

---

Codigo/BiotLab/Service/FornecedorService.cs
Codigo/BiotLab/core/Service/IFornecedorService.cs

Ainda falta modificar o programm e o DTO que serão adicionados junto com as proximas issues no csu manter fornecedor.

Adicionado o FornecedorService e o IFornecedorService ao projeto

---

Codigo/BiotLab/BiotLabWeb/Controllers/GaiolaharemController.cs

O codigo não esta funcionando, pois esta faltando a implementação do IPesquisadorService.

Implementado GaiolaharemController

---

Codigo/BiotLab/BiotLabWeb/Models/FornecedorViewModel.cs
Codigo/BiotLab/BiotLabWeb/Models/InstituicaoViewModel.cs
Codigo/BiotLab/BiotLabWeb/Program.cs
Codigo/BiotLab/BiotLabWeb/Views/Fornecedor/Create.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Fornecedor/Delete.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Fornecedor/Details.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Fornecedor/Edit.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Fornecedor/Index.cshtml
Codigo/BiotLab/core/DTO/FornecedorDTO.cs

adicionado a correção de alguns parametros no caso de uso manter institição para ficar compativel com o banco de dados e alteração em nomes de comentarios

Adicionado as views do fornecedor e outras correções

---

Codigo/BiotLab/BiotLabWeb/Views/Harem/Create.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Harem/Delete.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Harem/Details.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Harem/Edit.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Harem/Index.cshtml

viwes do harem. problemas para conectar ao banco

closed #97

---

Codigo/BiotLab/BiotLabWeb/Models/EntradaanestesicoViewModel.cs
Codigo/BiotLab/BiotLabWeb/Views/Entradaanestesico/Create.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Entradaanestesico/Delete.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Entradaanestesico/Details.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Entradaanestesico/Edit.cshtml
Codigo/BiotLab/BiotLabWeb/Views/Entradaanestesico/Index.cshtml

Foi Adicionado as Views(Index,create,edit,delete,detaisl)

Adicionado as viwes de Entradaanestesico

---

Codigo/BiotLab/Service/GaiolaharemService.cs
Codigo/BiotLab/ServiceTests/GaiolaharemServiceTests.cs

Precisei refazer o GaiolaharemService (faltou alguns campos obrigatorios) e corrigir bugs no GaiolaharemServiceTests

Corrigido os bugs do GaiolaharemServiceTests

---

Codigo/BiotLab/BiotLabTests/Controllers/EntradaanestesicoControllerTests.cs
Codigo/BiotLab/BiotLabTests/Controllers/GaiolaharemControllerTests.cs
Codigo/BiotLab/BiotLabWeb/Controllers/GaiolaharemController.cs

Corrigido os erros do GaiolaharemControllerTests , Foi alterado a controller( Estava faltando fazer referencia a pesquisador)

Corrigido os erros do GaiolaharemControllerTests.

---

Codigo/BiotLab/BiotLabWeb/Program.cs

adicionado cookie de autenticação, acabei adicionado um fator de segurança a mais.

---

Codigo/BiotLab/BiotLabWeb/Areas/Identity/Pages/Account/Login.cshtml
Codigo/BiotLab/BiotLabWeb/Program.cs
Codigo/BiotLab/BiotLabWeb/Views/Shared/_Layout.cshtml

Adição de ajustes na tela de login e estilização

---

Codigo/BiotLab/BiotLabWeb/Areas/Identity/Pages/Account/ForgotPassword.cshtml
Codigo/BiotLab/BiotLabWeb/Areas/Identity/Pages/Account/Register.cshtml

Telas Estilizadas!

---

Codigo/BiotLab/BiotLabWeb/Models/BioterioViewModel.cs
Codigo/BiotLab/BiotLabWeb/Views/Bioterio/Create.cshtml

Adicionado o busca Cep
